name: Release
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1

jobs:
  release:
    runs-on: ubuntu-22.04
    name: Release
    env:
      OUTPUT_DIR: ${{ github.workspace }}/builds
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        PREFIX=${OUTPUT_DIR} make artifacts
        ( cd ${OUTPUT_DIR}; sha256sum * ) > "${GITHUB_WORKSPACE}/SHA256SUMS"
        mv "${GITHUB_WORKSPACE}/SHA256SUMS" "${OUTPUT_DIR}/SHA256SUMS"
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        SHA256SUM_OF_SHA256SUM=$(sha256sum ${OUTPUT_DIR}/SHA256SUMS | cut -d ' ' -f 1)
        RELEASE_TAG="${GITHUB_REF##*/}"
        MINIMAL_TAR=$(ls -1 ${OUTPUT_DIR} | grep container2wasm-v | head -1)
        MINIMAL_TAR_LIST=$(tar --list -vvf ${OUTPUT_DIR}/${MINIMAL_TAR})
        cat <<EOF > ${GITHUB_WORKSPACE}/release-note.txt
        ${RELEASE_TAG}

        (TBD)

        ## About the tarball binaries
        Extract it to a path like \`/usr/local/bin/\` or \`~/bin/\`

        <details>
        <summary>list of files</summary>

        \`\`\`
        ${MINIMAL_TAR_LIST}
        \`\`\`

        </details>

        ---
        
        The sha256sum of SHA256SUM is \`${SHA256SUM_OF_SHA256SUM}\`

        EOF
        ASSET_FLAGS=()
        ls -al ${OUTPUT_DIR}/
        for F in ${OUTPUT_DIR}/* ; do
          ASSET_FLAGS+=("-a" "$F")
        done
        hub release create "${ASSET_FLAGS[@]}" -F ${GITHUB_WORKSPACE}/release-note.txt --draft "${RELEASE_TAG}"
